name: .NET WPF
 
 
on: [push]
 
 
jobs:
  build:
 
 
    runs-on: windows-latest
 
 
    steps:
    - uses: actions/checkout@v3
      with:
         ref: "6.0.7"
    - name: Install Nuget
      uses: nuget/setup-nuget@v
      with:
        nuget-version: '5.x'
      
    - name: Build
      run:  .\build.cmd -c Release -pack -prepareMachine /p:Platform=x64
